### ISSUE TITLE
Valitaanko "Cron"?

### ISSUE THREAD

**Issue by Vicky-Lind** [LehtJan/SmartHome-Application#9]
## Cron

**Comment by Vicky-Lind** [comment]
Hyvät:
* voi määrittää aikavyöhykkeen
* ottaa kesä/talvi ajan huomioon

**Comment by LehtJan** [comment]
Tämä voisi olla oika valinta tähän projektiin

**Comment by Vicky-Lind** [comment]
Keskustelimme asiasta lisää slackissä ja valittiin Cron-kirjasto. Voi lukea lisää valinnasta ja vertailusta wikisivulta kohdasta [Kommunikointi ja työkalut](https://github.com/LehtJan/SmartHome-Application/wiki/Kommunikointi-ja-Työkalut-🛠%EF%B8%8F).
